<?php
/**
 * @file
 * seven module.
 */

define('SEVEN_ADMIN_PATH', 'admin/config/system/seven');
define('SEVEN_USER_STATUS_PENDING', 1);
define('SEVEN_USER_STATUS_CONFIRMED', 2);

module_load_include('inc', 'seven', 'seven.user');

/**
 * Implements hook_menu().
 */
function seven_menu() {
    return [
        'user/%user/seven/message' => [
            'access arguments' => ['administer seven'],
            'file' => 'seven.admin.inc',
            'page arguments' => ['seven_admin_test_form', 'user', 1],
            'page callback' =>'backdrop_get_form',
            'title' => t('Send Message'),
            'type' => MENU_LOCAL_TASK,
        ],
        SEVEN_ADMIN_PATH => [
            'access arguments' => ['administer seven'],
            'description' => t('Administer seven settings'),
            'file' => 'seven.admin.inc',
            'page arguments' => ['seven_admin_form'],
            'page callback' => 'backdrop_get_form',
            'title' => 'seven',
        ],
        SEVEN_ADMIN_PATH . '/settings' => [
            'title' => t('Settings'),
            'type' => MENU_DEFAULT_LOCAL_TASK,
            'weight' => -10,
        ],
        SEVEN_ADMIN_PATH . '/test' => [
            'access arguments' => ['administer seven'],
            'description' => 'Test seven functionality',
            'file' => 'seven.admin.inc',
            'page arguments' => ['seven_admin_test_form'],
            'page callback' => 'backdrop_get_form',
            'title' => t('Send Test Message'),
            'type' => MENU_LOCAL_TASK,
        ],
    ];
}

/**
 * Implements hook_menu_alter().
 * https://docs.backdropcms.org/api/backdrop/core%21modules%21system%21system.api.php/function/hook_menu_alter/1
 */
function seven_menu_alter(&$callbacks) {
    $callbacks['user/%user/edit/default']['title'] = 'Account';
    $callbacks['user/%user/edit/default']['type'] = MENU_DEFAULT_LOCAL_TASK;

    $callbacks['user/%user/edit/seven']['file'] = 'seven.pages.inc';
    $callbacks['user/%user/edit/seven']['module'] = 'seven';
    $callbacks['user/%user/edit/seven']['page arguments'] = [1];
    $callbacks['user/%user/edit/seven']['page callback'] = 'seven_user_settings';
    $callbacks['user/%user/edit/seven']['title'] = 'seven SMS';

    $callbacks['user/%user/edit/seven']['access arguments'] = ['edit own sms number'];
    $callbacks['user/%user/edit/seven']['type'] = MENU_LOCAL_TASK;
}

/**
 * Implements hook_permission().
 */
function seven_permission() {
    return [
        'administer seven' => [
            'description' => t('Administer seven configuration'),
            'title' => t('Administer seven'),
        ],
        'edit own sms number' => [
            'description' => t('User may edit own phone number'),
            'title' => t('Edit phone number'),
        ],
    ];
}

/**
 * Access callback for seven account editing.
 */
function seven_edit_access($account) {
    return user_edit_access($account) && user_access('edit own sms number', $account);
}

/**
 * Sends SMS via seven.
 * @param string $to
 *   The phone number of the recipient
 * @param string $text
 *   The text to send to the recipient
 * @return bool
 *   TRUE or FALSE if the message was successfully sent.
 */
function seven_send_sms($to, $text) {
    return seven_request('sms', compact('text', 'to'));
}

/**
 * Makes text-to-speech call via seven.
 * @param string $to
 *   The phone number of the recipient
 * @param string $text
 *   The text to send to the recipient
 * @return bool
 *   TRUE or FALSE if the message was successfully sent.
 */
function seven_send_voice($to, $text) {
    return seven_request('voice', compact('text', 'to'));
}

/**
 * Executes a command using the seven REST API.
 * @param string $endpoint
 *   The seven API endpoint to request.
 * @param array $data
 *   The request data for sending to the API.
 * @return bool
 *   TRUE if the command executed correctly, FALSE otherwise.
 */
function seven_request($endpoint, $data = []) {
    $config = config('seven.settings');
    $apiKey = $config->get('seven_api_key');

    if (!$apiKey) return false;

    switch ($endpoint) {
        case 'sms':
            $data['from'] = $config->get('seven_from');
        case 'voice':
    }

    $ch = curl_init('https://gateway.seven.io/api/' . $endpoint);
    $options = [
        CURLOPT_HTTPHEADER => [
            'Accept: application/json',
            'Content-Type: application/json',
            'X-Api-Key: ' . $apiKey,
        ],
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_POSTFIELDS => json_encode($data),
    ];

    try {
        curl_setopt_array($ch, $options);
        $res = curl_exec($ch);
        backdrop_set_message($res);
        $res = json_decode($res);
        if (100 !== (int)$res->success)
            watchdog('seven', 'Error during the HTTP request: ' . $res->success);
        curl_close($ch);
        return true;
    } catch (Exception $e) {
        watchdog('seven', $e->getMessage(), [], WATCHDOG_ERROR);

        backdrop_set_message(t('seven has returned the error: @error.', [
            '@error' => $e->getMessage(),
        ]), 'error');

        return false;
    }
}

/**
 * Checks if a given phone number already exists in the database.
 * @param string $number
 *   The sender's phone number.
 * @result boolean
 *   TRUE if it exists, FALSE otherwise.
 */
function seven_verify_duplicate_number($number) {
    $result = seven_select_query_number($number)
        ->execute()
        ->fetchObject();

    return $result && $result->phone === $number;
}

function seven_select_query_number($number) {
    return db_select('seven_user', 't')
        ->fields('t')
        ->condition('t.phone', $number);
}

/**
 * Determines if a number is associated with a user account.
 * @param string $number
 *   The phone number we are searching for.
 * @results bool
 *   TRUE or FALSE based on query.
 */
function seven_verify_number($number) {
    $result = seven_select_query_number($number)
        ->condition('t.status', SEVEN_USER_STATUS_CONFIRMED)
        ->execute()
        ->fetchObject();

    return !empty($result->uid);
}

/**
 * Implements hook_views_api().
 */
function seven_views_api() {
    return [
        'api' => 3,
        'path' => backdrop_get_path('module', 'seven'),
    ];
}

/**
 * Implements hook_config_info() for backdrop.
 */
function seven_config_info() {
    return [
        'seven.settings' => [
            'group' => t('Configuration'),
            'label' => t('seven Settings'),
        ],
    ];
}
